export const imageHelpers = {
  generateImageFileName: (provider: string): string => {
    const uniqueId = Math.random().toString(36).substring(2, 8);
    return `${provider}-${uniqueId}`.replace(/[^a-z0-9-]/gi, "");
  },

  shareOrDownload: async (
    imageData: string,
    provider: string
  ): Promise<void> => {


    const fileName = imageHelpers.generateImageFileName(provider);
    let blob: Blob | null = null;

    try {
      // For URLs (both http and local), fetch the image
      const url = imageData.startsWith('http') 
        ? imageData 
        : window.location.origin + imageData;

      const response = await fetch(url);
      
      if (!response.ok) throw new Error(`Failed to fetch image: ${response.statusText}`);
      
      blob = await response.blob();


      if (!blob) throw new Error('Failed to create image blob');

      const file = new File([blob], `${fileName}.png`, { type: "image/png" });


      if (navigator.share) {

        await navigator.share({
          files: [file],
          title: `Image generated by ${provider}`,
        });
      } else {

        throw new Error("Share API not available");
      }
    } catch (error) {
      // Fall back to download for any error (including share cancellation)
      console.error("Error sharing/downloading:", error);
      if (!blob) throw new Error('No image data available for download');
      
      const blobUrl = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = `${fileName}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(blobUrl);
    }
  },

  formatModelId: (modelId: string): string => {
    return modelId.split("/").pop() || modelId;
  },
};
