export type LayoutMode = "left-right" | "right-left" | "prompt-top" | "prompt-bottom" | "mobile-optimized";
export type BorderStyle = "solid" | "dashed" | "dotted" | "none";
export type ShadowStyle = "none" | "subtle" | "medium" | "large" | "glow";
export type TextAlign = "left" | "center" | "right";
export type PromptAlignment = "left" | "center" | "right";
export interface DesignSettings {
    background_color?: string;
    background_opacity?: number;
    background_gradient?: string;
    background_image?: string;
    container_padding?: number;
    container_padding_top?: number;
    container_padding_right?: number;
    container_padding_bottom?: number;
    container_padding_left?: number;
    border_radius?: number;
    shadow_style?: ShadowStyle;
    sidebar_background_color?: string;
    max_width?: number;
    max_height?: number;
    scale_factor?: number;
    layout_mode?: LayoutMode;
    prompt_section_width?: number;
    prompt_section_height?: number;
    prompt_gallery_spacing?: number;
    gallery_section_height?: number;
    prompt_background_color?: string;
    prompt_border_style?: BorderStyle;
    prompt_border_color?: string;
    prompt_border_width?: number;
    prompt_border_radius?: number;
    prompt_text_color?: string;
    prompt_font_family?: string;
    prompt_font_size?: number;
    prompt_placeholder_color?: string;
    prompt_section_alignment?: PromptAlignment;
    submit_button_background_color?: string;
    submit_button_text_color?: string;
    submit_button_hover_background_color?: string;
    prompt_input_background_color?: string;
    prompt_input_border_style?: BorderStyle;
    prompt_input_border_color?: string;
    prompt_input_border_width?: number;
    prompt_input_border_radius?: number;
    prompt_input_text_color?: string;
    prompt_input_font_family?: string;
    prompt_input_font_size?: number;
    prompt_input_placeholder_color?: string;
    header_enabled?: boolean;
    header_alignment?: TextAlign;
    logo_enabled?: boolean;
    logo_url?: string;
    logo_height?: number;
    logo_border_width?: number;
    logo_border_color?: string;
    logo_border_radius?: number;
    brand_name?: string;
    brand_name_enabled?: boolean;
    brand_name_color?: string;
    brand_name_font_family?: string;
    brand_name_font_size?: number;
    title_enabled?: boolean;
    title_text?: string;
    title_color?: string;
    title_font_family?: string;
    title_font_size?: number;
    cta_text?: string;
    cta_enabled?: boolean;
    cta_font_family?: string;
    cta_font_size?: number;
    cta_color?: string;
    iframe_width?: string;
    iframe_height?: string;
    iframe_border?: boolean;
    iframe_border_width?: number;
    iframe_border_color?: string;
    iframe_border_radius?: number;
    iframe_shadow?: ShadowStyle;
    iframe_loading?: "lazy" | "eager";
    iframe_sandbox?: string;
    iframe_referrerpolicy?: string;
    iframe_allowtransparency?: boolean;
    iframe_scrolling?: "auto" | "yes" | "no";
    uploader_enabled?: boolean;
    uploader_max_images?: number;
    uploader_background_color?: string;
    uploader_border_style?: BorderStyle;
    uploader_border_color?: string;
    uploader_border_width?: number;
    uploader_border_radius?: number;
    uploader_text_color?: string;
    uploader_font_family?: string;
    uploader_font_size?: number;
    uploader_icon_style?: string;
    uploader_primary_text?: string;
    uploader_secondary_text?: string;
    suggestions_enabled?: boolean;
    suggestions_count?: number;
    suggestion_background_color?: string;
    suggestion_text_color?: string;
    suggestion_border_style?: BorderStyle;
    suggestion_border_color?: string;
    suggestion_border_width?: number;
    suggestion_border_radius?: number;
    suggestion_font_family?: string;
    suggestion_font_size?: number;
    suggestion_shadow_style?: ShadowStyle;
    suggestion_arrow_icon?: boolean;
    gallery_background_color?: string;
    gallery_border_radius?: number;
    gallery_spacing?: number;
    gallery_columns?: number;
    gallery_max_images?: number;
    gallery_shadow_style?: ShadowStyle;
    gallery_font_family?: string;
    gallery_font_size?: number;
    gallery_container_border_enabled?: boolean;
    gallery_container_border_width?: number;
    gallery_container_border_color?: string;
    gallery_container_border_style?: BorderStyle;
    gallery_container_border_radius?: number;
    gallery_image_border_enabled?: boolean;
    gallery_image_border_width?: number;
    gallery_image_border_color?: string;
    gallery_image_border_style?: BorderStyle;
    gallery_image_border_radius?: number;
    overlay_enabled?: boolean;
    overlay_download_enabled?: boolean;
    overlay_reference_enabled?: boolean;
    overlay_background_color?: string;
    overlay_icon_color?: string;
    overlay_font_family?: string;
    overlay_font_size?: number;
    mobile_layout_mode?: LayoutMode;
    mobile_gallery_columns?: number;
    mobile_font_scale?: number;
    demo_enabled?: boolean;
    demo_upload_message?: string;
    demo_generation_message?: string;
    demo_loop_count?: number;
    demo_click_to_dismiss?: boolean;
    lead_capture_enabled?: boolean;
    lead_step1_title?: string;
    lead_step1_placeholder?: string;
    lead_step2_title?: string;
    lead_step2_name_placeholder?: string;
    lead_step2_phone_placeholder?: string;
    lead_modal_background_color?: string;
    lead_modal_text_color?: string;
    lead_modal_border_radius?: number;
    lead_modal_font_family?: string;
    lead_modal_font_size?: number;
    primary_color?: string;
    secondary_color?: string;
    font_family?: string;
    base_font_size?: number;
}
export declare const defaultDesignSettings: DesignSettings;
export interface DesignTheme {
    name: string;
    description?: string;
    background_color?: string;
    background_opacity?: number;
    background_gradient?: string;
    background_image?: string;
    container_padding?: number;
    container_padding_top?: number;
    container_padding_right?: number;
    container_padding_bottom?: number;
    container_padding_left?: number;
    border_radius?: number;
    shadow_style?: ShadowStyle;
    sidebar_background_color?: string;
    max_width?: number;
    max_height?: number;
    scale_factor?: number;
    header_enabled?: boolean;
    header_alignment?: TextAlign;
    logo_enabled?: boolean;
    logo_url?: string;
    logo_height?: number;
    logo_border_width?: number;
    logo_border_color?: string;
    logo_border_radius?: number;
    brand_name?: string;
    brand_name_enabled?: boolean;
    brand_name_color?: string;
    brand_name_font_family?: string;
    brand_name_font_size?: number;
    title_enabled?: boolean;
    title_text?: string;
    title_color?: string;
    title_font_family?: string;
    title_font_size?: number;
    cta_text?: string;
    cta_enabled?: boolean;
    cta_font_family?: string;
    cta_font_size?: number;
    cta_color?: string;
    layout_mode?: LayoutMode;
    prompt_section_width?: number;
    prompt_section_height?: number;
    prompt_gallery_spacing?: number;
    iframe_width?: string;
    iframe_height?: string;
    iframe_border?: boolean;
    iframe_border_width?: number;
    iframe_border_color?: string;
    iframe_border_radius?: number;
    iframe_shadow?: ShadowStyle;
    iframe_loading?: "lazy" | "eager";
    iframe_sandbox?: string;
    iframe_referrerpolicy?: string;
    iframe_allowtransparency?: boolean;
    iframe_scrolling?: "auto" | "yes" | "no";
    uploader_enabled?: boolean;
    uploader_max_images?: number;
    uploader_background_color?: string;
    uploader_border_style?: BorderStyle;
    uploader_border_color?: string;
    uploader_border_width?: number;
    uploader_border_radius?: number;
    uploader_text_color?: string;
    uploader_font_family?: string;
    uploader_font_size?: number;
    uploader_icon_style?: string;
    uploader_primary_text?: string;
    uploader_secondary_text?: string;
    prompt_background_color?: string;
    prompt_border_style?: BorderStyle;
    prompt_border_color?: string;
    prompt_border_width?: number;
    prompt_border_radius?: number;
    prompt_text_color?: string;
    prompt_font_family?: string;
    prompt_font_size?: number;
    prompt_placeholder_color?: string;
    prompt_section_alignment?: PromptAlignment;
    submit_button_background_color?: string;
    submit_button_text_color?: string;
    submit_button_hover_background_color?: string;
    prompt_input_background_color?: string;
    prompt_input_border_style?: BorderStyle;
    prompt_input_border_color?: string;
    prompt_input_border_width?: number;
    prompt_input_border_radius?: number;
    prompt_input_text_color?: string;
    prompt_input_font_family?: string;
    prompt_input_font_size?: number;
    prompt_input_placeholder_color?: string;
    suggestions_enabled?: boolean;
    suggestions_count?: number;
    suggestion_background_color?: string;
    suggestion_text_color?: string;
    suggestion_border_style?: BorderStyle;
    suggestion_border_color?: string;
    suggestion_border_width?: number;
    suggestion_border_radius?: number;
    suggestion_font_family?: string;
    suggestion_font_size?: number;
    suggestion_shadow_style?: ShadowStyle;
    suggestion_arrow_icon?: boolean;
    gallery_background_color?: string;
    gallery_border_radius?: number;
    gallery_spacing?: number;
    gallery_columns?: number;
    gallery_max_images?: number;
    gallery_shadow_style?: ShadowStyle;
    gallery_font_family?: string;
    gallery_font_size?: number;
    gallery_container_border_enabled?: boolean;
    gallery_container_border_width?: number;
    gallery_container_border_color?: string;
    gallery_container_border_style?: BorderStyle;
    gallery_container_border_radius?: number;
    gallery_image_border_enabled?: boolean;
    gallery_image_border_width?: number;
    gallery_image_border_color?: string;
    gallery_image_border_style?: BorderStyle;
    gallery_image_border_radius?: number;
    overlay_enabled?: boolean;
    overlay_download_enabled?: boolean;
    overlay_reference_enabled?: boolean;
    overlay_background_color?: string;
    overlay_icon_color?: string;
    overlay_font_family?: string;
    overlay_font_size?: number;
    mobile_layout_mode?: LayoutMode;
    mobile_gallery_columns?: number;
    mobile_font_scale?: number;
    demo_enabled?: boolean;
    demo_upload_message?: string;
    demo_generation_message?: string;
    demo_loop_count?: number;
    accent_color?: string;
    lead_capture_enabled?: boolean;
    lead_step1_title?: string;
    lead_step1_placeholder?: string;
    lead_step2_name_placeholder?: string;
    lead_step2_phone_placeholder?: string;
    lead_modal_background_color?: string;
    lead_modal_text_color?: string;
    lead_modal_border_radius?: number;
    lead_modal_font_family?: string;
    lead_modal_font_size?: number;
    primary_color?: string;
    secondary_color?: string;
    font_family?: string;
    base_font_size?: number;
}
export declare const getCompleteTheme: (theme: DesignTheme) => DesignSettings;
export declare const designThemes: DesignTheme[];
export declare const fontOptions: {
    value: string;
    label: string;
    category: string;
    weight: string;
}[];
export declare const loadGoogleFont: (fontFamily: string, weights?: string) => void;
export declare const getFontsByCategory: (category?: string) => {
    value: string;
    label: string;
    category: string;
    weight: string;
}[];
export declare const fontOptionsArray: {
    value: string;
    label: string;
    category: string;
    weight: string;
}[];
export declare const fontCategories: {
    value: string;
    label: string;
}[];
export type WidgetStyle = "modern" | "minimal" | "classic" | "bold" | "playful";
export declare const stylePresets: Record<WidgetStyle, Partial<DesignSettings>>;
export declare const hexToRgba: (hex: string, opacity?: number) => string;
export declare const getBackgroundColor: (color?: string, opacity?: number) => string;
export declare const getEffectivePadding: (settings: DesignSettings) => {
    top: number;
    right: number;
    bottom: number;
    left: number;
};
export declare const getPaddingCSS: (settings: DesignSettings) => string;
export declare const DEFAULT_THEMES: DesignTheme[];
export declare const generateTheme: (name: string) => DesignTheme;
export interface Template {
    id?: string;
    name: string;
    description: string;
    category: string;
    category_description?: string;
    subcategories: string[];
    subcategory_descriptions?: Record<string, string>;
    example_images: string[];
    example_prompts: string[];
    status?: 'active' | 'pending_review' | 'verification_needed';
    user_id?: string;
    created_at?: string;
    updated_at?: string;
}
export interface TemplateCategory {
    name: string;
    subcategories: {
        name: string;
        templates: Template[];
    }[];
}
export interface LayoutProps {
    config: DesignSettings;
    prompt: string;
    setPrompt: (prompt: string) => void;
    isLoading: boolean;
    suggestions: {
        text: string;
    }[];
    referenceImages: string[];
    generatedImages: {
        image: string | null;
    }[];
    fullPage?: boolean;
    deployment?: boolean;
    containerWidth?: number;
    instanceId: string;
    onGenerateGallery: () => void;
    onPromptSubmit: () => void;
    onSuggestionClick: (suggestion: {
        text: string;
    }) => void;
    onImageUpload: (image: string | null) => void;
    onImageRemove: (index: number) => void;
    onRefreshSuggestions: () => void;
    isSubmissionLimitReached?: boolean;
    submissionCount?: number;
    maxSubmissions?: number;
    hideInMobile?: boolean;
}
